config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'home/index'
  devise_for :users, controllers: { omniauth_callbacks: 'ocalls' }

  get 'products/userview', to: 'products#userview'
  get 'products/redirect_after_sign_in', to: 'products#redirect_after_sign_in'
  get 'products/check_role', to: 'products#check_role'
  get 'users/:id/payment_history' => 'users#payment_history', as: :payment_history
  
  
  resources :charges do
    collection do
      get :cards_list
    end
  end
  
  resources :orders 
  resources :carts, only: [:show] do
    collection do
      get :add_to_cart
      get :iterate_quantity
      get :remove_item_from_cart
    end
  end

  resources :products do
    resources :comments
    collection do
      get :by_category
      get :order
    end
  end

  # resources :users, only: [:show]

  resources :categories, except: [:edit, :update] do
    collection do
      get :list_cat, as: :list_cat
    end
  end
  resources :users do
    resources :addresses 
  end
  root 'products#userview'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
 

app/models/user.rb
class User < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :addresses 
  has_one  :cart, dependent: :destroy
  has_one  :customer, dependent: :destroy
  has_many :user_charges
  has_many :orders
  has_many :user_cards, dependent: :destroy
  after_create :send_msg

  accepts_nested_attributes_for :addresses, allow_destroy: true

  # validate :password_complexity
  validates :first_name, :last_name, :dob, :email, :mobile, presence: true
  
  # after_create :assign_cart
  #after_create :send_msg, :send_mail

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2] 

  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      #user.name = auth.info.name   # assuming the user model has a name
      #user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    # Uncomment the section below if you want users to be created if they don't exist
    unless user
      first_name = data['name'].split(" ")[0]
      last_name = data['name'].split(" ")[1] 
      user = User.new(first_name: first_name,
        last_name: last_name,
        email: data['email'],
        uid: access_token['uid'],
        provider: access_token['provider'],
        password: Devise.friendly_token[0,20]
      )
      user.save(validate: false)
    end
    user
  end

  private

  def assign_cart
    create_cart
  end

  def send_msg
    client = Twilio::REST::Client.new('ACb2ad07724169ab5a936792cab72db14c', 'c36f5a2288b4ff5bacce781ed0519d2f')
    $client.api.account.messages.create(
    from: '+18476968891',
    to: '+917987392544',
    body: 'Hey there! You are Successfully Login in OneShop.'
    )
  end

  def send_mail
    UserMailer.welcome_email(self).deliver_now
  end

  
  
  def password_complexity
    # Regexp extracted from https://stackoverflow.com/questions/19605150/regex-for-password-must-contain-at-least-eight-characters-at-least-one-number-a
    return if password.blank? || password =~ /^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{6,20}$/

    errors.add :password, 'Complexity requirement not met. Length should be 6-20 characters and include: 1 uppercase, 1 lowercase, 1 digit and 1 special character'
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	

  def index
    @users = User.all
  end 

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       # redirect_to @
    else
      render 'edit'
    end
  end

	def show
  	@user = User.find(params[:id])
	end

  # def new
  #   @user = User.new 
  # end

  def edit
    @user = User.find(params[:id])
    @products = @user.cart.carts_products
  end
  
  def destroy
    @user = User.find(params[:id])
    @user_id = @user.id 
    @user.destroy
    #redirect_to categories_path
  end

  def payment_history
    @user = User.find(params[:id])
    @payment_history = @user.user_charges
  end
 
	private
	def user_params
		params.require(:user).permit(addresses_attributes: [:id, :name, :mobile, :pincode, :address, :city, :state, :address_type, :_destroy])
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_address_fields.html.erb
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_PLACES_KEY']%>&libraries=places&callback=activateSearch"></script>
<div class="col-xs-8 nested-fields" id="address_fields">
  <p class="field">
    <%= f.label :name %> <br/>
    <%= f.text_field :name, :required => true %>
  </p>
  
  <p class="field">
    <%= f.label :mobile %><br/>
    <%= f.number_field :mobile, :required => true  %>
  </p>    
  <p class="field">
    <%= f.label :address %><br/>
    <%= f.text_field :address, class: "address_field", id: "search_place" %>
  </p><br/>
  <p class="field">
    <%= f.label :city %><br/>
    <%= f.text_field :city, class: "address_field" %>
  </p><br/>
  <p class="field">
    <%= f.label :pincode %><br/>
    <%= f.number_field :pincode %>
  </p><br/>
  <p class="field">
    <%= f.label :state %><br/>
    <%= f.text_field :state, class: "address_field" %>
  </p><br/>
  <p class="field">
    <%= f.label :address_type %><br />
    <%= f.label :address_type, "Home", :value => "Home"  %>
    <%= f.radio_button :address_type, 'Home' %>
    <%= f.label :address_type, "Work", :value => "Work" %>
    <%= f.radio_button :address_type, 'Work' %>
  </p>
  <%= link_to_remove_association "remove address", f %>
</div>

app/views/users/_addresses_view.html.erb
<% count = 1 %>
<div>
		<% @user.addresses.each do |address| %>
	<div id="address_<%= address.id%>">
	 Address-<%= count %>
		<div><%= address.name %>  <span style="background-color: grey; padding: 1px; color: white;"><%= address.address_type %></span> <%= address.mobile %> </div>
		<div><%= address.address%>, <%= address.city %>, <%= address.state %>, <%= address.pincode %></div>
		<%= link_to "Delete address", user_address_path(@user, address),:method => :delete, class: "btn btn-sm btn-danger", remote: true %>
		<hr>
	</div>
	<% count += 1%>
	<% end %>
</div>

app/views/users/_order_summary.html.erb
<div>

    <h3>Order Summary</h3>

<table class="table">
  <tr>
    <th>Prdouct</th>
    <th>Name</th>
    <th>Price</th>
    <th>Quantity</th>
    <th>Total</th>
  </tr>
 
  <% total = 0 %>
  <% @products.each do |product| %>
    <tr>
      <td><%= image_tag Product.find(product.product_id).pictures[0], width: '50px', height: '50px' %></td>
      <td><%= Product.find(product.product_id).name %></td>
      <td><%= Product.find(product.product_id).price %></td>
      <td><%= product.quantity %></td>
      <td><%= (Product.find(product.product_id).price.to_i) * (product.quantity.to_i) %></td>
      <% total += (Product.find(product.product_id).price.to_i) * (product.quantity.to_i) %>
    </tr>
  <% end %>
  <tr>
    <th>Grand Total</th>
    <th></th>
    <th></th>
    <th></th>
    <th><%= total %></th>
  </tr>
</table>
<hr>
</div>

app/views/users/destroy.js.erb
$('.user-tr-<%= @user_id %>').remove()

app/views/users/edit.html.erb
<h1>Check out</h1>

<%= form_with model: [@user], local: true do |form| %>
<div>
  <h3 class="text-success"><%= @user.first_name%> signed in.</h3>
  <div class="mt-4" id="addresses">
    <% if @user.addresses %>
      <%= render 'addresses_view', locals: {user: @user} %>
    <% else %>
      <%= form.fields_for :addresses do |address| %>
        <%= render 'users/address_fields', :f => address %>
      <% end %>
    <% end %>
    <div class='links'>
      <%= link_to_add_association 'add address', form, :addresses, style: "font-size:15px", class: "btn btn-primary", id: "add_address" %>
    </div>
  </div>

  <%= render 'order_summary' %>
        
  <p>
    <%= form.submit "Submit Address", class: "btn btn-primary" %>
  </p>   
</div>
<% end %>

  <p>
    <%= link_to "PAY", new_charge_path, class: "btn btn-primary" %>
    <%= link_to "PAY With Save Cards", cards_list_charges_path, class: "btn btn-primary" %> 
  </p>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
    
</head>
<body>
  <center>
    <h1> User Details</h1>
  </center>
  <table class="table table-striped">

    <thead>
      <tr >
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>Mobile</th>
        <th>Payment History</th>
        <th>Action</th>   
      </tr>
    </thead>

    <tbody class="user-listing">
      <% @users.each do |user| %>
        <tr class="user-tr-<%= user.id %>">
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.mobile %></td>
        <% if user.stripe_customer_id? %>
          <td><%= link_to 'Payment History', payment_history_path(user.id) %></td> 
        <%else%>
          <td></td>
        <%end%>

        <td><%= link_to 'Destroy', user_path(user.id), method: :delete, remote: true, data: { confirm:'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</body>
</html>

app/views/users/payment_history.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
    
</head>
<body>
  <center>
    <h1> Payment History</h1>
  </center>
  <table class="table table-striped">

    <thead>
      <tr >
        <th>Payment Number</th>
        <th>Amount</th>
        <th>Description</th>
        <th>Payment Date</th>

      </tr>
    </thead>

    <tbody class="user-listing">
      <% @payment_history.each do |ph| %>
        <tr>
        <td><%= ph.stripe_charge_id %></td>
        <td><%= ph.amount %></td>
        <td><%= ph.description %></td>
        <% date = ph.created_at %>
        <td><%= date.to_time.strftime(' %b %d %Y %H:%M %Z ') %></td>
          
        
       </tr>
      <% end %>
    </tbody>
  </table>
</body>
</html>

app/views/users/show.html.erb
<p class="text-info" style="font-size: 25px; font-weight: bold;"><%= @user.first_name.capitalize + " " + @user.last_name.capitalize %></p>
<p><strong>DoB: </strong><%= @user.dob %></p>
<p><strong>Email: </strong><%= @user.email %></p>
<p><strong>Mobile: </strong><%= @user.mobile %></p>

<%= link_to "Edit profile", edit_user_registration_path, class: "btn btn-success" %>