config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'home/index'
  devise_for :users, controllers: { omniauth_callbacks: 'ocalls' }

  get 'products/userview', to: 'products#userview'
  get 'products/redirect_after_sign_in', to: 'products#redirect_after_sign_in'
  get 'products/check_role', to: 'products#check_role'
  get 'users/:id/payment_history' => 'users#payment_history', as: :payment_history
  
  
  resources :charges do
    collection do
      get :cards_list
    end
  end
  
  resources :orders 
  resources :carts, only: [:show] do
    collection do
      get :add_to_cart
      get :iterate_quantity
      get :remove_item_from_cart
    end
  end

  resources :products do
    resources :comments
    collection do
      get :by_category
      get :order
    end
  end

  # resources :users, only: [:show]

  resources :categories, except: [:edit, :update] do
    collection do
      get :list_cat, as: :list_cat
    end
  end
  resources :users do
    resources :addresses 
  end
  root 'products#userview'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
 

app/models/address.rb
class Address < ApplicationRecord
	belongs_to :user
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user,    dependent: :destroy
  has_many :carts_products
  has_many :products, through: :carts_products
end

app/models/carts_product.rb
class CartsProduct < ApplicationRecord
  belongs_to :cart 
  belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
  validates :name, presence:true, uniqueness: { case_sensitive: false }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
  belongs_to :user  
  validates :your_comment, presence:true

  delegate :first_name, :dob, :last_name, :to => :user, :prefix => true
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :user
end

app/models/order.rb
class Order < ApplicationRecord

 belongs_to :user

end

app/models/product.rb
class Product < ApplicationRecord
  # mount_uploader :picture, PictureUploader
  has_many_attached :pictures

  paginates_per 9

  belongs_to :category

  has_many :comments, dependent: :destroy

  has_many :carts_products, dependent: :destroy
  has_many :carts, through: :carts_products 

  validates :name, :description, :price, :pictures, :category_id, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 1 }
  validate :white_list

  # def to_param
  #   name
  # end
  def to_param
    "#{id}-#{name}".parameterize
    #[id, name.parameterize].join("-")
  end

  def white_list
  	pictures.each do |picture|
	  	if !picture.content_type.in?(%w(image/jpeg image/png image/jpg))
	      errors.add(:pictures, 'Must be a of jpeg, jpg or png format')
	    end
		end
  end

  def self.search(search)
    where("name LIKE ? OR description LIKE ? ", "%#{search}%", "%#{search}%") 
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :addresses 
  has_one  :cart, dependent: :destroy
  has_one  :customer, dependent: :destroy
  has_many :user_charges
  has_many :orders
  has_many :user_cards, dependent: :destroy
  after_create :send_msg

  accepts_nested_attributes_for :addresses, allow_destroy: true

  # validate :password_complexity
  validates :first_name, :last_name, :dob, :email, :mobile, presence: true
  
  # after_create :assign_cart
  #after_create :send_msg, :send_mail

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2] 

  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      #user.name = auth.info.name   # assuming the user model has a name
      #user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    # Uncomment the section below if you want users to be created if they don't exist
    unless user
      first_name = data['name'].split(" ")[0]
      last_name = data['name'].split(" ")[1] 
      user = User.new(first_name: first_name,
        last_name: last_name,
        email: data['email'],
        uid: access_token['uid'],
        provider: access_token['provider'],
        password: Devise.friendly_token[0,20]
      )
      user.save(validate: false)
    end
    user
  end

  private

  def assign_cart
    create_cart
  end

  def send_msg
    client = Twilio::REST::Client.new('ACb2ad07724169ab5a936792cab72db14c', 'c36f5a2288b4ff5bacce781ed0519d2f')
    $client.api.account.messages.create(
    from: '+18476968891',
    to: '+917987392544',
    body: 'Hey there! You are Successfully Login in OneShop.'
    )
  end

  def send_mail
    UserMailer.welcome_email(self).deliver_now
  end

  
  
  def password_complexity
    # Regexp extracted from https://stackoverflow.com/questions/19605150/regex-for-password-must-contain-at-least-eight-characters-at-least-one-number-a
    return if password.blank? || password =~ /^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{6,20}$/

    errors.add :password, 'Complexity requirement not met. Length should be 6-20 characters and include: 1 uppercase, 1 lowercase, 1 digit and 1 special character'
  end

end

app/models/user_card.rb
class UserCard < ApplicationRecord
 belongs_to :user
end

app/models/user_charge.rb
class UserCharge < ApplicationRecord
  belongs_to :user
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def list_cat
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    # @category_id = @category.id
    if @category.save
      #redirect_to categories_path
    else
      render 'new'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @cat_id = @category.id
    @category.destroy
    #redirect_to categories_path
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end
end 

app/helpers/address_helper.rb
module AddressHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/catogery_helper.rb
module CatogeryHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/omnis_helper.rb
module OmnisHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.erb
<tr class="cat-tr-<%= category.id %>">
  <td><%= category.name %></td>
  <td><%= link_to 'Destroy', category_path(category.id), method: :delete, remote: true, data: { confirm:'Are you sure?' } %></td>
</tr>
  

app/views/categories/_category_error.html.erb
<% if @category.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>
    <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/categories/_form.html.erb
<%= render 'category_error' %>
<%= bootstrap_form_with scope: :category, url: categories_path, method: :POST, remote: true do |form| %>
  
    <%= form.text_field :name, class: "cat-text" %>
 
    <%= form.submit class: "btn btn-primary btn-xm" %> <%= link_to 'Back', products_url,class: "btn btn-warning btn-xm" %>
  
<% end %>

app/views/categories/_list.html.erb
<!-- <div class="container-fluid col-md-3" style="background-color: green;">
  <h1>Category</h1>
  <h1>List</h1>
</div> -->
<div class="modal-dialog modal-lg list-88" style="background-color: white;"> 
   <div class="modal-body container-fluid col-md-6" style="background-color: white  ;">
        <% @categories.each do |category| %> 
          <div class="container-fluid col-md-3">
            <%= link_to category.name, by_category_products_path(category_id: category.id), remote: true  %>
          </div>
        <%end%>     
   </div>
</div>

app/views/categories/create.js.erb
$('.categories-listing').append("<%= j (render partial: 'category', locals: {category: @category}) %>")
$('.cat-text').val('')

app/views/categories/destroy.js.erb
$('.cat-tr-<%= @cat_id %>').remove()

app/views/categories/index.html.erb
<%= link_to 'Add New Category', new_category_path, remote: true, class: "btn btn-primary btn-xs" %>
<div class="add-category"></div>
<!DOCTYPE html>
<html>
<head>
  <title></title>
    
</head>
<body>
  <center>
    <h1> Product Catogery </h1>
  </center>
  <table class="table table-striped">

    <thead>
      <tr >
        <th>Name</th>
        <th>Action</th>
      </tr>
    </thead>

    <tbody class="categories-listing">
      <% @categories.each do |c| %>
        <%= render partial: 'category', locals: {category: c }%>
      <% end %>
    </tbody>
  </table>
</body>
</html>

app/views/categories/list_cat.js.erb
$("#modal-window").html("<%= j (render '/categories/list') %>");
$("#modal-window").modal(); 

app/views/categories/new.html.erb
<center>
  <h2>Add Category</h2>
</center><hr>
<%= render 'form' %>

app/views/categories/new.js.erb
$('.add-category').html("<%= j (render 'form') %>")