config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'home/index'
  devise_for :users, controllers: { omniauth_callbacks: 'ocalls' }

  get 'products/userview', to: 'products#userview'
  get 'products/redirect_after_sign_in', to: 'products#redirect_after_sign_in'
  get 'products/check_role', to: 'products#check_role'
  get 'users/:id/payment_history' => 'users#payment_history', as: :payment_history
  
  
  resources :charges do
    collection do
      get :cards_list
    end
  end
  
  resources :orders 
  resources :carts, only: [:show] do
    collection do
      get :add_to_cart
      get :iterate_quantity
      get :remove_item_from_cart
    end
  end

  resources :products do
    resources :comments
    collection do
      get :by_category
      get :order
    end
  end

  # resources :users, only: [:show]

  resources :categories, except: [:edit, :update] do
    collection do
      get :list_cat, as: :list_cat
    end
  end
  resources :users do
    resources :addresses 
  end
  root 'products#userview'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
 

app/models/product.rb
class Product < ApplicationRecord
  # mount_uploader :picture, PictureUploader
  has_many_attached :pictures

  paginates_per 9

  belongs_to :category

  has_many :comments, dependent: :destroy

  has_many :carts_products, dependent: :destroy
  has_many :carts, through: :carts_products 

  validates :name, :description, :price, :pictures, :category_id, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 1 }
  validate :white_list

  # def to_param
  #   name
  # end
  def to_param
    "#{id}-#{name}".parameterize
    #[id, name.parameterize].join("-")
  end

  def white_list
  	pictures.each do |picture|
	  	if !picture.content_type.in?(%w(image/jpeg image/png image/jpg))
	      errors.add(:pictures, 'Must be a of jpeg, jpg or png format')
	    end
		end
  end

  def self.search(search)
    where("name LIKE ? OR description LIKE ? ", "%#{search}%", "%#{search}%") 
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # before_action :check_privileges!, only: [:index, :new, :create, :edit, :destroy]
  def index
    #@product = Product.find(params[:id])
    @products = Product.all.page params[:page]
    if params[:search]
      @products = Product.search(params[:search]).order("created_at DESC")
    else
      @products = Product.all.order("created_at DESC")
    end
  end

  def show
    @categories = Category.all
    @product = Product.find(params[:id])
    @comments = @product.comments
    @comment = @product.comments.build
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to :action => 'index' #redirect_to products_path  

    else
        render 'new' #render :action => 'new'
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path
   else
      render 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product_id = @product.id
    @product.destroy
    #redirect_to products_path
  end

  def userview 
    @categories = Category.all
    @products = Product.all.page params[:page]
  end

  def by_category
    @categories = Category.all
    @category  = Category.find(params[:category_id])
    @product   = @category.products
  end

  def redirect_after_sign_in
    if current_user.role == "Admin"
      redirect_to  products_url
    else
      redirect_to products_userview_url
    end
  end
   
  
  def order
    # respond_to do |format|
    #   format.html
    #   format.js
    # end
  end   
  
  private
  def product_params
    params.require(:product).permit(:name, :description, :price, :number_of_units, :category_id, :pictures => [])
  end

  def check_privileges!
    unless current_user.role == "Admin"
      redirect_to "/", notice: 'You dont have enough permissions to be here' 
    end
  end


end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_byCategory.html.erb
<% @product.each do |product| %>
  <div class="col-xs-4 col-xs-offset-0 col-lg-4 col-lg-offset-0">
    <div id="myCarousel<%= product.id %>" class="carousel slide" data-ride="carousel" style="height: 300px" >
    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <%= image_tag(product.pictures[0], {:style => "height:300px;"})%>
      </div>

      <% product.pictures.drop(1).each do |picture| %>
        <div class="item">
          <%= image_tag(picture, {:style => "height:300px;"})%>
        </div>
      <% end %>
    </div>

    <!-- Left and right controls -->
      <a class="left carousel-control" href="#myCarousel" data-target="#myCarousel<%= product.id %>" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
        <span  class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" data-target="#myCarousel<%= product.id %>" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
        <span  class="sr-only">Next</span>
      </a>
    </div>    
    <div class="product_name">
      <h4><%= product.name %></h4>
    </div>    
    <div class="price_line">
      <h4 class="price"> ₹ <%=product.price%></h4>
    </div>
    <% if current_user.role != "Admin" %>
    <%= link_to 'Show More', product_path(product) %> | <%= link_to 'Add to Cart', add_to_cart_carts_path(product_id: product.id) %>
    <% end %>  
  </div>
<%end%>

app/views/products/_category.html.erb
<div style="float: right;">
 <%= select_tag 'by_category', options_for_select(all_categories.map{ |c| [c.name, c.id] }), { prompt: 'Select ptoduct Category', id: 'category-filter', class: "btn btn-warning btn-xs"} %>
</div>

<script type="text/javascript">
  $('#category-filter').on('change', function(){
    $.ajax({
      type: 'GET',
      url: '/products/by_category?category_id=' + this.value
    });
  });
</script>

app/views/products/_error.html.erb
<% if @product.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
    <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/products/_form.html.erb
<%= bootstrap_form_with scope: :product, multipart: true, url: products_path, local: true do |form| %>
  <%= form.text_field :name, :required => true, placeholder: "Product Name" %> 
  <%= form.number_field :price, :required => true, :min=>1 %> 
  <%= form.file_field :pictures, multiple: true, id: :product_picture %>
  <%= form.number_field :number_of_units, :required => true, :min=> 1%>
  <%= form.collection_select :category_id,  Category.all, :id, :name, { prompt: 'Select promptoduct Category'} %>
  <%= form.text_area :description, rows: 10, cols:30 %>
  <%= form.submit data: { "disable-with": "Saving..." },class: "btn btn-success btn-xm" %>   
<% end %>

app/views/products/_search.html.erb
<%= form_tag(products_path, method: 'get') do %>
      <%= text_field_tag(:search, params[:search]) %>
      <%= submit_tag("Search", name: nil) %>
<% end %>

app/views/products/by_category.html.erb
<% @product.each do |product| %>
  <div class="col-xs-4 col-xs-offset-0 col-lg-4 col-lg-offset-0">
    <div class="product_img img-responsive">
      <%= image_tag product.picture_url, width: '200px', height:'250px'%>
    </div>
    <div class="product_name">
      <h4><%= product.name %></h4>
    </div>    
    <div class="price_line">
      <h4 class="price"> ₹ <%=product.price%></h4>
    </div>
    <%= link_to 'Show More', product_path(product) %>
  </div>
<%end%>

app/views/products/by_category.js.erb
$('.by-category').html("<%= escape_javascript(render 'byCategory') %>")

app/views/products/destroy.js.erb
$('.product-id-<%= @product_id  %>').remove()



// $('.p tr td').on('ajax:success', function(event){
//     $(this).closest('tr').remove();
// })

app/views/products/edit.html.erb
<%= link_to 'Back', products_url, class: "btn btn-primary btn-xs" %>
<center>
  <h2>Update Product</h2>
</center><hr>
<%= render 'error' %>
<%= render 'form' %>

app/views/products/index.html.erb
<% @products.each do |product| %>
  <div class="col-xs-4 min-hg product-id-<%= product.id  %>" style="width: 150px, height: 250px">
    <div id="myCarousel<%= product.id %>" class="carousel slide" data-ride="carousel" style="height: 300px" >
    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active" >
        <%= image_tag(product.pictures[0], {:style => "height:300px;"})%>
      </div>

      <% product.pictures.drop(1).each do |picture| %>
        <div class="item" >
          <%= image_tag(picture, {:style => "height:300px;"})%>
        </div>
      <% end %>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-target="#myCarousel<%= product.id %>" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span  class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-target="#myCarousel<%= product.id %>" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span  class="sr-only">Next</span>
    </a>
  </div>
    <div class="product_name">
      <h4><%= product.name %></h4>
    </div>    
    <div class="price_line">
      <h4 class="price"> ₹ <%=product.price%></h4>
    </div>
    <div>
      <%= product.category && product.category.name %>
    </div>
    <%= link_to 'Edit', edit_product_path(product) %> | <%= link_to 'Show More', product_path(product), class: "btn btn-link" %>| <%= link_to 'Destroy', product, method: :delete, remote: true, data: { confirm:'Are you sure?' } %> 
  </div>
<%end%>

<% if @products.blank? %>
  <h4 class="text-danger">There are no products containing the term <%= params[:search] %>.</h4>
<% end %>

<!-- <center>
  <%#= paginate @products, window: 2 %><br>
</center> --> 
 

app/views/products/new.html.erb
<div class="col-lg-7">
  <%= link_to 'Back', products_url, class: "btn btn-primary btn-xs" %> 
<center>
  <h2>Add Product</h2>
</center><hr>
<%= render 'error' %>
<%= render 'form'%>
</div>

app/views/products/order.js.erb
$("#modal-window").html("<%= j (render '/layouts/modal') %>");
$("#modal-window").modal(); 

app/views/products/show.html.erb
<h5>Product Details</h5>
<div class="col-xs-4 min-hg1">
  <div id="myCarousel<%= @product.id %>" class="carousel slide" data-ride="carousel" style="height: 300px">
    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <%= image_tag (@product.pictures[0]), {:style => "height:300px;"} %>
      </div>

      <% @product.pictures.drop(1).each do |picture| %>
        <div class="item">
          <%= image_tag (picture), {:style => "height:300px;"} %>
        </div>
      <% end %>
    </div>

    <!-- Left and right controls -->
      <a class="left carousel-control" href="#myCarousel" data-target="#myCarousel<%= @product.id %>" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
        <span  class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" data-target="#myCarousel<%= @product.id %>" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
        <span  class="sr-only">Next</span>
      </a>
    </div>
  <div>
    <p><strong>Name:-</strong><%= @product.name %></p>
  </div>
  <div>         
    <p><strong>Price:-</strong><%= @product.price %></p>
  </div><br>
</div>
<div class="col-xs-8 min-hg">
  <div>         
    <p><strong>Descriptioin:-</strong><%= @product.description %></p>
  </div>  
</div>
<div class=all-comments>
  <h4>User Comments:</h4>
  <% @comments.each do |comment| %>
    <% if comment.id %>
      <%= render partial: 'comments/comment', locals: {comment: comment } %>
    <% end %>
  <% end %>
</div>

<% if current_user %>
  <div class="user-comment">
    <%= render 'comments/form' %>
  </div>
<% end %>

<!-- Yha par local me jo comment pass kiya hai white vala
vo [do] ke baad vala hai ise hum commnet bana ke partial par pass kr rhe hai
kyuki partial par hum commnet se value nikal rhe hai -->


<!-- <p><strong><%#= link_to "Add Comment", new_product_comment_url(@product), remote: true, class: "btn btn-success btn-sm"   %></strong> </p> -->

app/views/products/userview.html.erb
<div class="flexslider">
  <ul class="slides">
    <li>
      <%= image_tag "s1.jpg" , :size => "400x300" %>   
    </li>
    <li>
      <%= image_tag "s2.jpg" , :size => "400x300" %>
    </li>
    <li>
      <%= image_tag "s3.jpg" , :size => "400x300" %>
    </li>
  </ul>
</div>

<% @products.each do |product| %>
  <div class="col-xs-3 min-hg">
    <div id="myCarousel<%= product.id %>" class="carousel slide" data-ride="carousel" style="height: 150px" >
      <!-- Wrapper for slides -->
      <div class="carousel-inner">
        <div class="item active">
          <%= image_tag(product.pictures[0], {:style => "height:150px;"})%>
        </div>
        <% product.pictures.drop(1).each do |picture| %>
          <div class="item">
            <%= image_tag(picture, {:style => "height:150px;"})%>
          </div>
        <% end %>
      </div>
    </div>   
    <!-- Left and right controls -->
      <!-- <a class="left carousel-control" href="#myCarousel" data-target="#myCarousel<%= product.id %>" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
        <span  class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" data-target="#myCarousel<%= product.id %>" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
        <span  class="sr-only">Next</span>
      </a>
    </div> -->

    <div class="product_name">
      <h4><%= product.name %></h4>
    </div>    
    <div class="price_line">
      <h4 class="price"> ₹ <%=product.price%></h4>
    </div>
    <%= link_to 'Show More', product_path(product), class: "btn btn-sm btn-success" %> <%= link_to 'Add to Cart', add_to_cart_carts_path(product_id: product.id), class: "btn btn-sm btn-primary" %> 
  </div>
<% end %>

<div id="login-window" class="modal fade" role="dialog"></div>
<div id="signup-window" class="modal fade" role="dialog"></div>

  <center>
  <%= paginate @products, window: 2 %><br>
  <!-- <h5><%= page_entries_info @products, entry_name: 'item' %></h5> -->
</center>
<% unless current_user %>
<script type="text/javascript">
  $( window ).load(function() {
    $("#login-window").html("<%= j (render '/layouts/login') %>");
    $("#login-window").modal();
  });
</script>
<% end %>
<script type="text/javascript">
  $('body').on('click', '#modal-signup',function(){
    $("#signup-window").html("<%= j (render '/layouts/signup') %>");
    $("#signup-window").modal();
  });
</script>