config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'home/index'
  devise_for :users, controllers: { omniauth_callbacks: 'ocalls' }

  get 'products/userview', to: 'products#userview'
  get 'products/redirect_after_sign_in', to: 'products#redirect_after_sign_in'
  get 'products/check_role', to: 'products#check_role'
  get 'users/:id/payment_history' => 'users#payment_history', as: :payment_history
  
  
  resources :charges do
    collection do
      get :cards_list
    end
  end
  
  resources :orders 
  resources :carts, only: [:show] do
    collection do
      get :add_to_cart
      get :iterate_quantity
      get :remove_item_from_cart
    end
  end

  resources :products do
    resources :comments
    collection do
      get :by_category
      get :order
    end
  end

  # resources :users, only: [:show]

  resources :categories, except: [:edit, :update] do
    collection do
      get :list_cat, as: :list_cat
    end
  end
  resources :users do
    resources :addresses 
  end
  root 'products#userview'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
 

app/models/address.rb
class Address < ApplicationRecord
	belongs_to :user
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user,    dependent: :destroy
  has_many :carts_products
  has_many :products, through: :carts_products
end

app/models/carts_product.rb
class CartsProduct < ApplicationRecord
  belongs_to :cart 
  belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
  validates :name, presence:true, uniqueness: { case_sensitive: false }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
  belongs_to :user  
  validates :your_comment, presence:true

  delegate :first_name, :dob, :last_name, :to => :user, :prefix => true
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :user
end

app/models/order.rb
class Order < ApplicationRecord

 belongs_to :user

end

app/models/product.rb
class Product < ApplicationRecord
  # mount_uploader :picture, PictureUploader
  has_many_attached :pictures

  paginates_per 9

  belongs_to :category

  has_many :comments, dependent: :destroy

  has_many :carts_products, dependent: :destroy
  has_many :carts, through: :carts_products 

  validates :name, :description, :price, :pictures, :category_id, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 1 }
  validate :white_list

  # def to_param
  #   name
  # end
  def to_param
    "#{id}-#{name}".parameterize
    #[id, name.parameterize].join("-")
  end

  def white_list
  	pictures.each do |picture|
	  	if !picture.content_type.in?(%w(image/jpeg image/png image/jpg))
	      errors.add(:pictures, 'Must be a of jpeg, jpg or png format')
	    end
		end
  end

  def self.search(search)
    where("name LIKE ? OR description LIKE ? ", "%#{search}%", "%#{search}%") 
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :addresses 
  has_one  :cart, dependent: :destroy
  has_one  :customer, dependent: :destroy
  has_many :user_charges
  has_many :orders
  has_many :user_cards, dependent: :destroy
  after_create :send_msg

  accepts_nested_attributes_for :addresses, allow_destroy: true

  # validate :password_complexity
  validates :first_name, :last_name, :dob, :email, :mobile, presence: true
  
  # after_create :assign_cart
  #after_create :send_msg, :send_mail

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2] 

  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      #user.name = auth.info.name   # assuming the user model has a name
      #user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    # Uncomment the section below if you want users to be created if they don't exist
    unless user
      first_name = data['name'].split(" ")[0]
      last_name = data['name'].split(" ")[1] 
      user = User.new(first_name: first_name,
        last_name: last_name,
        email: data['email'],
        uid: access_token['uid'],
        provider: access_token['provider'],
        password: Devise.friendly_token[0,20]
      )
      user.save(validate: false)
    end
    user
  end

  private

  def assign_cart
    create_cart
  end

  def send_msg
    client = Twilio::REST::Client.new('ACb2ad07724169ab5a936792cab72db14c', 'c36f5a2288b4ff5bacce781ed0519d2f')
    $client.api.account.messages.create(
    from: '+18476968891',
    to: '+917987392544',
    body: 'Hey there! You are Successfully Login in OneShop.'
    )
  end

  def send_mail
    UserMailer.welcome_email(self).deliver_now
  end

  
  
  def password_complexity
    # Regexp extracted from https://stackoverflow.com/questions/19605150/regex-for-password-must-contain-at-least-eight-characters-at-least-one-number-a
    return if password.blank? || password =~ /^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{6,20}$/

    errors.add :password, 'Complexity requirement not met. Length should be 6-20 characters and include: 1 uppercase, 1 lowercase, 1 digit and 1 special character'
  end

end

app/models/user_card.rb
class UserCard < ApplicationRecord
 belongs_to :user
end

app/models/user_charge.rb
class UserCharge < ApplicationRecord
  belongs_to :user
end

app/helpers/address_helper.rb
module AddressHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/catogery_helper.rb
module CatogeryHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/omnis_helper.rb
module OmnisHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_category_search.html.erb
<% if user_signed_in? && (current_user.role == "Admin") %>
  <h3 align="left"><strong>Welcome Admin</strong></h3>
    <div class="col-lg-3">
      <div class="well sidebar-nav ">
        <ul class="nav nav-list">
          <li class="nav-header"></li>
          <li><%= link_to 'Add New Product', new_product_path %></li>
          <li><%= link_to 'Add New Category', category_new_path %></li>
        </ul>
      </div>
    </div>
      <% elsif user_signed_in? && current_user.role != "Admin"%>
        <div class="col-lg-3">
          <div class="well sidebar-nav ">
            <ul class="nav nav-list">
              <li class="nav-header"></li>
              <li><%= link_to "All Product", products_userview_path  %></li>
              <li><%= link_to "Product Category", "#"  %></li>
                <ul>
                  <% @categories.each do |c| %>
                    <li><%= link_to  c.name, by_category_products_path(category_id: c.id)  %></li>
                    <%end%>
                </ul>
              <li><%= link_to "How to Order", "/"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      <% else %>
      <% end -%>

<%= render '/layouts/nav' %>

  
      

app/views/layouts/_login.html.erb
<div class="modal-dialog modal-xm" style="background-color: white;">
  <div class="modal-header">
     <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
     <h3 id="myModalLabel" ></h3>
   </div>
  <div class="modal-body col-sm-12">
    <h2>Log in</h2>
    <%= bootstrap_form_for(:user, as: :user, url: session_path(:user)) do |f| %> 
      <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
      <%= f.password_field :password, autocomplete: "current-password" %>
      <%= f.submit "Log in", class: "btn btn-primary btn-xm" %> <button type="button" id="modal-signup" class="btn btn-primary btn-xm">Sign Up</button>    
    <% end %>

  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
</div>

app/views/layouts/_modal.html.erb
<div class="modal-dialog modal-lg" style="background-color: white;">
  <div class="modal-header">
     <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
     <h3 id="myModalLabel" ><span class="glyphicon glyphicon-shopping-cart"></span> How to Order</h3>
   </div>
   <div class="modal-body">
    <p><b>Please Follow the Instruction</b></p>
     <ul>
       <li>First Sign Up OR Login to OneShop</li>
       <li>Visit the product detail page for an item you wish to buy</li>
       <li>Tap Add to Cart.</li>
       <li>When you've finished adding items to your cart, tap the Shopping Cart icon.</li>
       <li>If you need to edit the items in your Cart, tap Save for later or Delete next to the item in the Cart.</li>
     </ul>
   </div>
   <div class="modal-footer">
     <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
   </div>
</div>

app/views/layouts/_odal.html.erb
<div class="modal-dialog modal-lg" style="background-color: mediumseagreen;">
  <div class="modal-header">
     <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
     <h3 id="myModalLabel" ><span class="glyphicon glyphicon-shopping-cart"></span> How to Order</h3>
   </div>
   <div class="modal-body">
    <p><b>Please Follow the Instruction</b></p>
     <ul>
       <li>First Sign Up OR Login to OneShop</li>
       <li>Visit the product detail page for an item you wish to buy</li>
       <li>Tap Add to Cart.</li>
       <li>When you've finished adding items to your cart, tap the Shopping Cart icon.</li>
       <li>If you need to edit the items in your Cart, tap Save for later or Delete next to the item in the Cart.</li>
     </ul>
   </div>
   <div class="modal-footer">
     <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
   </div>
</div>

app/views/layouts/_signup.html.erb
<div class="modal-dialog modal-xm" style="background-color: white;">
  <div class="modal-header">
     <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
     <h3 id="myModalLabel" >Sign up</h3>
   </div>
  <div class="modal-body col-sm-12">
    <%= bootstrap_form_for(:user, as: :user, url: registration_path(:user),label_errors: true, inline_errors: true) do |f| %> 
      <%#= devise_error_messages! %> 
      <%= f.text_field :first_name %>   
      <%= f.text_field :last_name %>   
      <%= f.date_field :dob %> 
      <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
      <%= f.password_field :password, autocomplete: "new-password",help: "Must be at least 6 characters long" %>
      <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
         <%= f.text_field :mobile %>
      <%= f.submit "Sign up", class: "btn btn-primary btn-xm" %>  <%= link_to "Back", "/users/sign_in",class: "btn btn-warning btn-xm" %>
    <% end %>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
     

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
      <%= content_for?(:title) ? yield(:title) : "One" %>
    </title>
    <script type="text/javascript">
      // var add_address_button = document.getElementById("add_address");
      // add_address_button.addEventListener("click", activateSearch);

      // var search = function(){
      // var input_field = document.getElementById("search_place");
      // input_field.addEventListener("focus", activateSearch);
      // }

      function activateSearch(){
        var input = document.getElementById("search_place");
        var autocomplete = new google.maps.places.Autocomplete(input);
      }
    </script>
    <!-- <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDbrQjJqOS5glOpnQgk9GcR0ePvVHJes-8&libraries=places&callback=activateSearch"></script> -->
    <!-- <script src="jquery.geocomplete.js"></script> -->
    <%= csrf_meta_tags %>
    <link href="css/bootstrap.min.css" rel="stylesheet" />
    <link href="css/navbar-fixed-side.css" rel="stylesheet" />
    <%= stylesheet_link_tag "application", :media => "all",'data-turbolinks-track' => true %>
    <%= javascript_include_tag "application",'data-turbolinks-track' => true %>
  </head>
  <body>
    <div class="navbar navbar-light bg-light navbar-static-top">
      <div class="container">
        <a class="navbar-brand" href="/" style="color: aqua;"><b>OneShop</b></a>
        <div>
          <%= form_tag(products_path, :method => "get", id: "search-form", class: "nav navbar-nav") do %>
            <%= text_field_tag :search, params[:search], placeholder: "Search Products", class: "form-control", :style=> "margin-top: 7px; padding-right: 170px; margin-left: 50px;"%>
            <%= submit_tag "Search", :name => nil, :style => "display: none;"%>
          <% end %>
        </div>
          <%= link_to 'List', 'javascript:void(0);', class: "btn btn-sm btn-success cat-list-btn", id: "list-77", remote: true, "data-toggle" => "modal", "data-target" => "my-modal" %>
        <% if !current_user %>
          <ul class="nav navbar-nav navbar-right">
            <ul class="dropdown">
              <button class="btn btn-primary dropdown-toggle" type="button"data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span>
              <span class="caret"></span></button>
                <ul class="dropdown-menu">
                  <li><span ></span><%= link_to 'Login', new_user_session_path %> </li> 
                  <li><span ></span><%= link_to 'Sign up', new_user_registration_path %> </li>
                </ul>
            </ul>
          </ul>
        <% end %>
        <% if user_signed_in? %>
          <ul class="nav navbar-nav navbar-right">
            <ul class="dropdown">
              <button class="btn btn-primary dropdown-toggle" type="button"data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span> Welcome! <%= current_user.first_name %>
              <span class="caret"></span></button>
                <ul class="dropdown-menu">
                  <li><span ></span><%= link_to 'My profile', user_path(current_user.id) %> </li>
                  <% if current_user.stripe_customer_id? %>
                    <li><%= link_to 'My Payment History', payment_history_path(current_user.id) %></li> 
                  <%end%>
                  <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>  
                </ul>
            </ul>
          </ul>
        <% end %>
      </div>
    </div>       
    <div class="container"> 
      <div class="row">
        <% if user_signed_in? && (current_user.role == "Admin") %>
          <div class="mg-top products-by-category">
            <strong>Welcome Admin</strong>
            <%= render '/products/category' %>
          </div>
          <div class="container-fluid">
           <div class="row">

          <div class="col-sm-3 col-lg-2">
            <div class="navbar navbar-default navbar-fixed-side ">
              <ul class="nav nav-list">
                <li class="nav-header"></li>
                <li><%= link_to 'Home', products_url%></li>
                <li><%= link_to 'Add New Product', new_product_path %></li>
                <li><%= link_to 'List of Category', categories_path %></li>
                <li><%= link_to 'List of Users', users_path %></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
        <% elsif user_signed_in? && current_user.role != "Admin"%>
          <div class="mg-top products-by-category">
            <%= render '/products/category' %>
          </div>
          <div class="col-lg-3">
            <div class="well sidebar-nav ">
              <ul class="nav nav-list">
                <li class="nav-header"></li>
                <% if current_user.cart %>
                  <li><%= link_to " My Cart", cart_path(current_user.cart)  %></li>
                <%end%>
                <li><%= link_to "All Product", products_userview_path  %></li>
                <li><%= link_to "Product Category", "#"  %></li>
                  <ul>
                    <% all_categories.each do |c| %>
                      <li><%= link_to  c.name, by_category_products_path(category_id: c.id), remote: true  %></li>
                    <%end%>
                  </ul>
                <li>
                  <%= link_to "How to Order", order_products_path, {:remote => true} %>
                </li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        <% end -%>
    <% if current_user %>    
      <div class="col-lg-9 by-category">
        <%= bootstrap_flash %>    
        <%= yield %>
      </div>
    <%else%>
      <div class="col-lg-12 by-category">
        <%= bootstrap_flash %>    
        <%= yield %>
      </div>
    <% end %>
      
    </div><!--/row-->
      <center>
        <footer>  
          <div class="container">
            <p>&copy; OakTree 2018</p>
          </div>        
        </footer>
      </center>
    </div> <!-- /container -->
    <div id="modal-window" class="modal fade" role="dialog"></div>
  </body>


  <script type="text/javascript">
  $('#list-77').mouseover(function(){
    $.ajax({
      type: 'GET',
      url: '/categories/list_cat'
    });
  });
</script>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>